"""Generate the AstrBot Dashboard plugin page from the web/ source tree.

`web/` is the single hand-edited frontend source (directly servable at
http://127.0.0.1:8180 without any build step). `pages/dashboard/` is a
generated artifact and must never be edited by hand:

- shared JS/CSS files are copied verbatim from `web/assets/`;
- `assets/style.css` is bundled self-contained (AstrBot plugin page
  sandbox cannot rely on `@import` sub-path resolution);
- environment adapter files come from `scripts/dashboard_overrides/`
  (bridge API layer + plugin-page index.html);
- both index.html get a content-hash `?v=` cache-busting stamp so the
  version never needs manual bumping.

Usage:
    python scripts/build_frontend.py           # regenerate artifacts
    python scripts/build_frontend.py --check   # verify artifacts are in sync (CI gate)
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = ROOT / "web"
WEB_ASSETS = WEB_ROOT / "assets"
PAGE_ROOT = ROOT / "pages" / "dashboard"
PAGE_ASSETS = PAGE_ROOT / "assets"
OVERRIDES = ROOT / "scripts" / "dashboard_overrides"

VERSION_PLACEHOLDER = "__ASSET_VERSION__"
VERSION_RE = re.compile(r"\?v=[0-9A-Za-z._-]+")
IMPORT_RE = re.compile(r'^@import\s+"(?P<path>[^"]+)";\s*$')


def bundle_style_css() -> bytes:
    """Inline every @import of web/assets/style.css into one self-contained file.

    Returns:
        UTF-8 bytes of the bundled stylesheet, LF line endings.

    Raises:
        ValueError: If style.css contains a line that is neither an @import
            nor blank (the shim must stay import-only so bundling stays trivial).
    """
    parts = [
        "/* GENERATED by scripts/build_frontend.py — edit web/assets/css/* instead. */\n"
    ]
    for line in (WEB_ASSETS / "style.css").read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        match = IMPORT_RE.match(line.strip())
        if not match:
            raise ValueError(
                f"web/assets/style.css must only contain @import lines, got: {line!r}"
            )
        rel = match.group("path")
        content = (WEB_ASSETS / rel).read_text(encoding="utf-8")
        parts.append(f"\n/* ==== {rel} ==== */\n\n{content.rstrip()}\n")
    return "".join(parts).encode("utf-8")


def generate_assets() -> dict[Path, bytes]:
    """Compute the full pages/dashboard/assets output set (relative path -> bytes)."""
    outputs: dict[Path, bytes] = {}
    for source in sorted(WEB_ASSETS.rglob("*")):
        if source.is_file():
            outputs[source.relative_to(WEB_ASSETS)] = source.read_bytes()
    outputs[Path("style.css")] = bundle_style_css()
    for override in sorted((OVERRIDES / "assets").rglob("*")):
        if override.is_file():
            outputs[override.relative_to(OVERRIDES / "assets")] = override.read_bytes()
    return outputs


def compute_version(assets: dict[Path, bytes]) -> str:
    """Derive the cache-busting ?v= stamp from generated asset content."""
    digest = hashlib.sha256()
    for rel in sorted(assets):
        digest.update(rel.as_posix().encode("utf-8"))
        digest.update(b"\0")
        digest.update(assets[rel])
        digest.update(b"\0")
    return digest.hexdigest()[:10]


def render_page_index(version: str) -> bytes:
    template = (OVERRIDES / "index.html").read_text(encoding="utf-8")
    if VERSION_PLACEHOLDER not in template:
        raise ValueError(
            f"dashboard index.html template lost its {VERSION_PLACEHOLDER} placeholder"
        )
    return template.replace(VERSION_PLACEHOLDER, version).encode("utf-8")


def render_web_index(version: str) -> bytes:
    """Restamp ?v= in web/index.html (source file, kept directly servable)."""
    text = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
    stamped, count = VERSION_RE.subn(f"?v={version}", text)
    if count == 0:
        raise ValueError("web/index.html has no ?v= cache-busting query to stamp")
    return stamped.encode("utf-8")


def build(check: bool = False) -> list[str]:
    """Write (or with check=True, only verify) every generated file.

    Returns:
        Repo-relative paths that were out of sync (empty means clean).
    """
    assets = generate_assets()
    version = compute_version(assets)

    outputs: dict[Path, bytes] = {
        PAGE_ASSETS / rel: content for rel, content in assets.items()
    }
    outputs[PAGE_ROOT / "index.html"] = render_page_index(version)
    outputs[WEB_ROOT / "index.html"] = render_web_index(version)

    stale = [
        path
        for path in PAGE_ASSETS.rglob("*")
        if path.is_file() and path not in outputs
    ]

    mismatches: list[str] = []
    for path in sorted(outputs):
        current = path.read_bytes() if path.is_file() else None
        if current != outputs[path]:
            mismatches.append(path.relative_to(ROOT).as_posix())
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(outputs[path])
    for path in sorted(stale):
        mismatches.append(f"{path.relative_to(ROOT).as_posix()} (stale)")
        if not check:
            path.unlink()

    return mismatches


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify generated artifacts match the source; exit 1 on drift without writing",
    )
    args = parser.parse_args(argv)

    mismatches = build(check=args.check)
    if args.check:
        if mismatches:
            print("Generated frontend artifacts are out of sync:")
            for item in mismatches:
                print(f"  {item}")
            print("Run: python scripts/build_frontend.py")
            return 1
        print("Generated frontend artifacts are in sync.")
        return 0

    if mismatches:
        print(f"Regenerated {len(mismatches)} file(s):")
        for item in mismatches:
            print(f"  {item}")
    else:
        print("Everything already up to date.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
